"""Synthetic NASA IMS-like datasets for controlled local benchmarks."""

from __future__ import annotations

import csv
import json
from collections import Counter
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

import numpy as np

from codigo.app.schemas.dataset import CommonManifestRecord
from codigo.app.schemas.executor_results import ManifestResult
from codigo.app.schemas.state import ArtifactRef

SYNTHETIC_NASA_SAMPLE_RATE_HZ = 20000
SYNTHETIC_NASA_CHANNELS = ["channel_1", "channel_2", "channel_3", "channel_4"]
SYNTHETIC_NASA_RUN_ID = "set_2_synthetic_binary"
SYNTHETIC_NASA_CONDITION_ID = "synthetic_temporal_binary"


def prepare_synthetic_nasa_ims_binary_dataset(
    raw_dir: str | Path,
    *,
    seed: int = 42,
    n_normal_files: int = 7,
    n_fault_files: int = 5,
    sample_count: int = 8192,
) -> dict[str, Any]:
    """Writes a small NASA IMS-like binary benchmark to ``raw_dir``.

    The dataset is intentionally synthetic. It keeps the timestamp-file layout,
    four-channel tabular format and 20 kHz sampling rate of NASA IMS set 2, but
    labels are controlled by construction and must not be presented as official
    NASA labels.
    """

    if n_normal_files < 3:
        raise ValueError("n_normal_files must be >= 3 to create train/validation/test")
    if n_fault_files < 1:
        raise ValueError("n_fault_files must be >= 1")
    if sample_count < 4096:
        raise ValueError("sample_count must be >= 4096")

    root = Path(raw_dir)
    target_dir = root / "2nd_test"
    target_dir.mkdir(parents=True, exist_ok=True)

    start = datetime(2004, 2, 12, 10, 32, 39)
    total_files = n_normal_files + n_fault_files
    file_summaries: list[dict[str, Any]] = []
    for index in range(total_files):
        timestamp = start + timedelta(minutes=10 * index)
        file_path = target_dir / timestamp.strftime("%Y.%m.%d.%H.%M.%S")
        label = "normal" if index < n_normal_files else "fault"
        frame = _synthetic_frame(
            index=index,
            total_files=total_files,
            n_normal_files=n_normal_files,
            sample_count=sample_count,
            seed=seed,
        )
        np.savetxt(file_path, frame, fmt="%.8f", delimiter="\t")
        file_summaries.append(
            {
                "path": file_path.as_posix(),
                "label": label,
                "file_index": index,
                "rms_channel_1": float(np.sqrt(np.mean(frame[:, 0] ** 2))),
            }
        )

    spec_path = root / "synthetic_dataset_spec.json"
    payload = {
        "dataset": "nasa_ims_bearing",
        "synthetic": True,
        "seed": seed,
        "n_normal_files": n_normal_files,
        "n_fault_files": n_fault_files,
        "sample_count": sample_count,
        "sample_rate_hz": SYNTHETIC_NASA_SAMPLE_RATE_HZ,
        "channels": SYNTHETIC_NASA_CHANNELS,
        "notes": (
            "Synthetic NASA IMS-like benchmark. File labels are generated by "
            "construction and are not official NASA IMS annotations."
        ),
        "files": file_summaries,
    }
    spec_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return payload | {"spec_path": spec_path.as_posix(), "raw_dir": root.as_posix()}


def generate_synthetic_nasa_ims_binary_manifest(
    raw_dir: str | Path,
    output_dir: str | Path,
    *,
    n_normal_files: int = 7,
    sample_count: int = 8192,
) -> ManifestResult:
    """Generates a common manifest for the synthetic NASA IMS-like benchmark."""

    root = Path(raw_dir)
    files = _timestamp_files(root)
    if not files:
        raise ValueError(f"no synthetic NASA IMS timestamp files found in {root}")
    if len(files) <= n_normal_files:
        raise ValueError("manifest requires at least one synthetic fault file")

    records = [
        _record_for_file(
            file_path,
            raw_dir=root,
            file_index=index,
            label="normal" if index < n_normal_files else "fault",
            sample_count=sample_count,
        )
        for index, file_path in enumerate(files)
    ]
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    manifest_path = output / "manifest.csv"
    _write_common_manifest(manifest_path, records)
    label_counts = dict(Counter(record.label for record in records))
    artifact = ArtifactRef(
        name="nasa_ims_synthetic_binary_manifest",
        artifact_type="manifest",
        path=manifest_path.as_posix(),
        producer="manifest_executor",
        metadata={
            "dataset": "nasa_ims_bearing",
            "synthetic": True,
            "n_rows": len(records),
            "sampling_rate_hz": SYNTHETIC_NASA_SAMPLE_RATE_HZ,
            **label_counts,
        },
    )
    return ManifestResult(
        executor_name="dataset_manifest",
        status="success",
        message="Synthetic NASA IMS-like binary manifest generated.",
        artifacts=[artifact],
        errors=[],
        state_updates={
            "manifest_path": manifest_path.as_posix(),
            "dataset_id": "nasa_ims_bearing",
            "adapter_id": "nasa_ims_synthetic_binary",
        },
        manifest_path=manifest_path.as_posix(),
        n_rows=len(records),
        label_counts=label_counts,
    )


def _synthetic_frame(
    *,
    index: int,
    total_files: int,
    n_normal_files: int,
    sample_count: int,
    seed: int,
) -> np.ndarray:
    rng = np.random.default_rng(seed + index)
    time = np.arange(sample_count, dtype=float) / SYNTHETIC_NASA_SAMPLE_RATE_HZ
    normal_progress = index / max(1, total_files - 1)
    fault_progress = max(0.0, (index - n_normal_files + 1) / max(1, total_files - n_normal_files))
    phase = rng.uniform(0.0, 2.0 * np.pi)

    base = (
        0.18 * np.sin(2.0 * np.pi * 118.0 * time + phase)
        + 0.045 * np.sin(2.0 * np.pi * 317.0 * time)
        + 0.018 * np.sin(2.0 * np.pi * 9.0 * time + phase / 2.0)
    )
    channel_1 = base * (1.0 + 0.08 * normal_progress)
    channel_1 += rng.normal(0.0, 0.024, size=sample_count)

    if fault_progress:
        channel_1 += _impact_train(
            sample_count=sample_count,
            fault_progress=fault_progress,
            rng=rng,
        )
        channel_1 += 0.012 * fault_progress * np.sin(2.0 * np.pi * 1450.0 * time)

    channel_2 = (
        0.16 * np.sin(2.0 * np.pi * 96.0 * time + phase / 3.0)
        + 0.03 * np.sin(2.0 * np.pi * 420.0 * time)
        + rng.normal(0.0, 0.026, size=sample_count)
    )
    channel_3 = (
        0.12 * np.cos(2.0 * np.pi * 74.0 * time + phase)
        + rng.normal(0.0, 0.028, size=sample_count)
    )
    channel_4 = (
        0.09 * np.sin(2.0 * np.pi * 52.0 * time)
        + rng.normal(0.0, 0.022, size=sample_count)
    )
    return np.column_stack([channel_1, channel_2, channel_3, channel_4])


def _impact_train(
    *,
    sample_count: int,
    fault_progress: float,
    rng: np.random.Generator,
) -> np.ndarray:
    impacts = np.zeros(sample_count, dtype=float)
    period = int(SYNTHETIC_NASA_SAMPLE_RATE_HZ / 245)
    amplitude = 0.026 + 0.07 * fault_progress
    start = int(rng.integers(0, period))
    for position in range(start, sample_count, period):
        jitter = int(rng.integers(-4, 5))
        impact_start = min(max(0, position + jitter), sample_count - 1)
        width = 4 + int(3 * fault_progress)
        stop = min(sample_count, impact_start + width)
        axis = np.arange(stop - impact_start, dtype=float)
        impacts[impact_start:stop] += amplitude * np.exp(-axis / max(1.0, width / 2.0))

    envelope = np.linspace(0.35, 1.0, sample_count)
    if fault_progress <= 0.25:
        envelope[: sample_count // 2] = 0.0
    return impacts * envelope


def _record_for_file(
    file_path: Path,
    *,
    raw_dir: Path,
    file_index: int,
    label: str,
    sample_count: int,
) -> CommonManifestRecord:
    timestamp_start = datetime.strptime(file_path.name, "%Y.%m.%d.%H.%M.%S")
    timestamp_end = timestamp_start + timedelta(
        seconds=sample_count / SYNTHETIC_NASA_SAMPLE_RATE_HZ
    )
    timestamp_key = file_path.name.replace(".", "_")
    return CommonManifestRecord(
        record_id=f"set_2_synth_{timestamp_key}",
        dataset="nasa_ims_bearing",
        source_path=file_path.as_posix(),
        source_format="txt",
        label=label,
        label_detail="synthetic_outer_race_like_degradation" if label == "fault" else None,
        condition_id=SYNTHETIC_NASA_CONDITION_ID,
        asset_id="bearing_1_synthetic",
        run_id=SYNTHETIC_NASA_RUN_ID,
        timestamp_start=timestamp_start,
        timestamp_end=timestamp_end,
        sampling_rate_hz=SYNTHETIC_NASA_SAMPLE_RATE_HZ,
        target_sample_rate_hz=SYNTHETIC_NASA_SAMPLE_RATE_HZ,
        channel_names=SYNTHETIC_NASA_CHANNELS,
        primary_channel="channel_1",
        n_channels=len(SYNTHETIC_NASA_CHANNELS),
        metadata_json={
            "synthetic": True,
            "file_index": file_index,
            "sample_count": sample_count,
            "source_layout": raw_dir.name,
            "official_nasa_labels": False,
        },
        notes=(
            "synthetic_nasa_ims_like_binary_benchmark; labels generated by "
            "construction, not official NASA IMS annotations"
        ),
    )


def _timestamp_files(raw_dir: Path) -> list[Path]:
    return sorted(
        [
            file_path
            for file_path in raw_dir.rglob("*")
            if file_path.is_file() and _looks_like_timestamp_file(file_path)
        ],
        key=lambda path: path.as_posix(),
    )


def _looks_like_timestamp_file(path: Path) -> bool:
    name = path.stem if path.suffix.lower() in {".txt", ".csv", ".tsv"} else path.name
    parts = name.split(".")
    return len(parts) == 6 and all(part.isdigit() for part in parts)


def _write_common_manifest(path: Path, records: list[CommonManifestRecord]) -> None:
    fieldnames = list(CommonManifestRecord.model_fields)
    with path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        for record in records:
            writer.writerow(_serialize_common_manifest_row(record))


def _serialize_common_manifest_row(record: CommonManifestRecord) -> dict[str, Any]:
    row: dict[str, Any] = {}
    for key, value in record.model_dump().items():
        if value is None:
            row[key] = ""
        elif isinstance(value, datetime):
            row[key] = value.isoformat()
        elif isinstance(value, (dict, list)):
            row[key] = json.dumps(value, sort_keys=True)
        else:
            row[key] = value
    return row
