"""Esquemas Pydantic compartidos por agentes, ejecutores y grafo."""

from codigo.app.schemas.agent_decisions import (
    CleaningDecision,
    EvaluationDecision,
    ModelingDecision,
    ReportDecision,
    ReportSection,
    StructuringDecision,
    SupervisorDecision,
)
from codigo.app.schemas.dataset import (
    DatasetManifest,
    DatasetManifestRow,
    FaultMetadata,
    SignalChannel,
)
from codigo.app.schemas.executor_results import (
    CleaningResult,
    EvaluationExecutorResult,
    ExecutorResult,
    ManifestResult,
    ModelingResult,
    ProfileResult,
    ReportExecutorResult,
    StructuringResult,
)
from codigo.app.schemas.state import (
    ArtifactRef,
    CleaningConfig,
    DatasetProfileSummary,
    EvaluationResult,
    HumanApproval,
    MetricsReport,
    ModelingConfig,
    PipelineError,
    ProjectContext,
    StateMessage,
    StructuringConfig,
    TFMStateModel,
)

__all__ = [
    "ArtifactRef",
    "CleaningDecision",
    "CleaningConfig",
    "CleaningResult",
    "DatasetManifest",
    "DatasetManifestRow",
    "DatasetProfileSummary",
    "EvaluationDecision",
    "EvaluationExecutorResult",
    "EvaluationResult",
    "ExecutorResult",
    "FaultMetadata",
    "HumanApproval",
    "ManifestResult",
    "MetricsReport",
    "ModelingDecision",
    "ModelingConfig",
    "ModelingResult",
    "PipelineError",
    "ProfileResult",
    "ProjectContext",
    "ReportDecision",
    "ReportExecutorResult",
    "ReportSection",
    "SignalChannel",
    "StateMessage",
    "StructuringDecision",
    "StructuringConfig",
    "StructuringResult",
    "SupervisorDecision",
    "TFMStateModel",
]
